apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - runtime-configmap.yaml
  - serviceaccount.yaml

  - bootstrap/db-schemas-configmap.yaml
  - bootstrap/db-schema-job.yaml
  - bootstrap/api-key-seed-job.yaml

  - apps/auth-service-deployment.yaml
  - apps/auth-service-service.yaml

  - apps/flag-service-deployment.yaml
  - apps/flag-service-service.yaml

  - apps/targeting-service-deployment.yaml
  - apps/targeting-service-service.yaml

  - apps/evaluation-service-deployment.yaml
  - apps/evaluation-service-service.yaml

  - apps/analytics-service-deployment.yaml
  - apps/analytics-service-service.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
