apiVersion: v1
kind: ServiceAccount
metadata:
  name: togglemaster-runtime
  namespace: togglemaster
  labels:
    app.kubernetes.io/part-of: togglemaster
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
automountServiceAccountToken: false
