apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: togglemaster
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: analytics-service
  ports:
    - name: http
      port: 8005
      targetPort: http
      protocol: TCP
