apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: flag-service
    app.kubernetes.io/part-of: togglemaster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flag-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flag-service
        app.kubernetes.io/part-of: togglemaster
    spec:
      serviceAccountName: togglemaster-runtime
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: flag-service
          image: 461624773988.dkr.ecr.us-east-1.amazonaws.com/flag-service:1cddda994a4e802e597129c632fd9cd05e37c70f
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: togglemaster-runtime-secrets
                  key: FLAG_DATABASE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-runtime-config
                  key: AUTH_SERVICE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 75m
              memory: 96Mi
            limits:
              cpu: 500m
              memory: 256Mi
